services:
  transcendenceDatabase:
    image: postgres:18.1-alpine3.23
    container_name: transcendenceDB
    restart: unless-stopped
    env_file:
      - database/.env
    ports:
      - "5432:5432"
    volumes:
    - transcendenceDatabaseVolume:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend
    container_name: transcendenceBackend
    restart: unless-stopped
    env_file:
      - backend/.env
    depends_on:
      - transcendenceDatabase
    ports:
      - "3000:3000"

volumes:
  transcendenceDatabaseVolume: