networks:
  transcendenceNetwork:
    driver: bridge

services:
  db_postgresql:
    image: postgres:16
    container_name: transcendenceDatabase
    restart: unless-stopped
    networks:
      - transcendenceNetwork
    ports:
      - "5432:5432"
    env_file:
      - database/.env
    volumes:
      - transcendenceDatabaseVolume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  backend_nestjs:
    build: ./backend
    restart: unless-stopped
    networks:
      - transcendenceNetwork
    env_file:
      - backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      db_postgresql:
        condition: service_healthy
    command: npm run start:dev

  frontend_nextjs:
    build: ./frontend
    restart: unless-stopped
    networks:
      - transcendenceNetwork
    env_file:
      - frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev

  server_nginx:
    image: nginx:stable
    restart: unless-stopped
    networks:
      - transcendenceNetwork
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend_nextjs
      - backend_nestjs
  
  llm_ollama:
    image: ollama/ollama:latest
    container_name: llm_ollama
    restart: unless-stopped
    networks:
      - transcendenceNetwork
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
volumes:
    transcendenceDatabaseVolume:
    ollama_data: