services:
  TranscendenceDatabase:
    image: postgres:18.1-alpine3.23
    container_name: TranscendenceDB
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
    - TranscendenceDatabaseVolume:/var/lib/postgresql/data

volumes:
  TranscendenceDatabaseVolume: